### ISSUE TITLE
In 16.04 network interfaces are renamed to enp0sX (or others) instead of eth0

### ISSUE THREAD

**Issue by q2dg** [ansible-roles/ansible-role-wol#1]
Maybe this fact should be taken into account in the playbook

**Comment by zenlord** [comment]
You can specify the variable {{ wol_interface }} and the role will work with whatever you supplied as the interface. I did create a pull request to replace a hardcoded 'eth0'-interface with the variable, but this patch will only impact the output in the terminal.

**Comment by q2dg** [comment]
Thanks!
I'll close this issue, then, if you don't mind.
